spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/zzanggoon
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      ddl-auto: validate
          ddl-auto: create
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
      format_sql: true
  profiles:
    active: dev
    # 구글 로그인 연동(application-oauth.properties 로딩)
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug

